android.useAndroidX=true
android.nonTransitiveRClass=true

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

kotlin.daemon.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
kotlin.incremental=true

android.compileSdk=36
android.minSdk=23
android.targetSdk=36

app.applicationId=com.snapreceipt.io
app.versionCode=6
app.versionName=1.0.4

java.version=17
kotlin.jvmTarget=17

# Maven publish coordinates for reusable modules
lib.groupId=com.skybound.space
lib.version=1.0.0
